In [10]:
import pandas as pd

In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [13]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,63,Female,Shorts,Clothing,31,New York,XL,Blue,Summer,3.62,Yes,Free Shipping,No,No,36,Bank Transfer,Annually
1,2,39,Male,Sandals,Footwear,85,Arizona,XL,Red,Fall,3.53,Yes,Express,Yes,Yes,12,Debit Card,Quarterly
2,3,40,Female,Hoodie,Clothing,72,Florida,L,White,Summer,3.61,No,Store Pickup,No,No,50,Venmo,Monthly
3,4,47,Male,Pants,Clothing,55,New York,XL,Pink,Winter,4.31,No,2-Day Shipping,No,No,40,PayPal,Monthly
4,5,22,Male,Dress,Clothing,36,New York,L,Black,Summer,4.72,Yes,Express,No,No,12,Venmo,Monthly

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3850 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [8]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3850.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,15,2,NaN,15,4,10,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Female,Blouse,Clothing,NaN,Colorado,M,Red,Spring,NaN,No,Standard,No,No,NaN,PayPal,Monthly
freq,NaN,NaN,1978,280,3105,NaN,275,1029,418,1085,NaN,2833,700,2188,2188,NaN,683,589
mean,1950.500000,43.525897,NaN,NaN,NaN,59.528718,NaN,NaN,NaN,NaN,3.806055,NaN,NaN,NaN,NaN,25.549231,NaN,NaN
std,1125.977353,15.091466,NaN,NaN,NaN,23.376079,NaN,NaN,NaN,NaN,0.588046,NaN,NaN,NaN,NaN,14.427428,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.030000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,30.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.400000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,43.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,26.000000,NaN,NaN
75%,2925.250000,56.000000,NaN,NaN,NaN,80.000000,NaN,NaN,NaN,NaN,4.220000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [9]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             50
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
df = pd.read_csv("customer_shopping_behavior.csv")

In [11]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [12]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(
    lambda x: x.fillna(x.median())
)

In [13]:
df['Review Rating'].isnull().sum()

np.int64(0)

In [14]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [15]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [16]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [17]:
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group']= pd.qcut(df['age'],q=4,labels=labels)

In [18]:
df[['age','age_group']].head(10)

   age    age_group
0   63       Senior
1   39        Adult
2   40        Adult
3   47  Middle-aged
4   22  Young Adult
5   26  Young Adult
6   38        Adult
7   28  Young Adult
8   22  Young Adult
9   52  Middle-aged

In [20]:
df.columns.tolist()

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'promo_code_used',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases',
 'age_group']

In [21]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [22]:
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0               Annually                      365
1              Quarterly                       90
2                Monthly                       30
3                Monthly                       30
4                Monthly                       30
5                Monthly                       30
6                Monthly                       30
7               Annually                      365
8              Bi-Weekly                       14
9         Every 3 Months                       90

In [23]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0               No              No
1              Yes             Yes
2               No              No
3               No              No
4               No              No
5              Yes             Yes
6               No              No
7               No              No
8               No              No
9              Yes             Yes

In [24]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [25]:
df=df.drop('promo_code_used',axis=1)

In [26]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [1]:
import pymysql

In [3]:
from sqlalchemy import create_engine

In [4]:
engine = create_engine(
    "mysql+pymysql://root:12345@localhost/customer_shopping_db"
)

In [5]:
with engine.connect() as conn:
    print("MySQL Connected Successfully!")

MySQL Connected Successfully!

In [14]:
df.to_sql(
    name='customer_shopping',
    con=engine,
    if_exists='replace',
    index=False
)

3900

In [15]:
print("Data uploaded to MySQL successfully!")

Data uploaded to MySQL successfully!